var app = angular.module('paginationApp', ['angularUtils.directives.dirPagination']);

app.controller('listData', function($scope) {
    var data = [
        {"ten":"Nguyen Quang A", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"1 phút trước"},
        {"ten":"Nguyen Quang B", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"10 phút trước"},
        {"ten":"Nguyen Quang C", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"20 phút trước"},
        {"ten":"Nguyen Quang D", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"30 phút trước"},
        {"ten":"Nguyen Quang E", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"40 phút trước"},
        {"ten":"Nguyen Quang F", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"50 phút trước"},
        {"ten":"Nguyen Quang G", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"1 giờ trước"},
        {"ten":"Nguyen Quang H", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"2 giờ trước"},
        {"ten":"Nguyen Quang I", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"1 ngày trước"},
        {"ten":"Nguyen Quang J", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"1 tháng trước"},
        {"ten":"Nguyen Quang K", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"1 năm trước"},
        {"ten":"Nguyen Quang L", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"2 năm trước"},
        {"ten":"Nguyen Quang M", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"3 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
        {"ten":"Nguyen Quang N", "sdt":"01633333549", "cua_hang":"Black Crow", "email":"quanghungleo@gmail.com", "thoi_gian":"4 năm trước"},
    ]
    $scope.data = data;
    $scope.serial = 1;
    $scope.indexCount = function(newPageNumber){
	    $scope.serial = newPageNumber * 10 - 9;
	}
});
